/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.vianna.aula.trabalhoprincipalclube.view;

import br.edu.vianna.aula.trabalhoprincipalclube.associado.subclass.Associado;
import br.edu.vianna.aula.trabalhoprincipalclube.associado.subclass.Dependente;
import br.edu.vianna.aula.trabalhoprincipalclube.database.connection.dao.DAOAssociado;
import br.edu.vianna.aula.trabalhoprincipalclube.database.connection.dao.DAODependente;
import br.edu.vianna.aula.trabalhoprincipalclube.view.dialog.JDCadastroAssociados;
import br.edu.vianna.aula.trabalhoprincipalclube.view.dialog.JDCadastroDependentes;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suporte
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jbHome1 = new javax.swing.JButton();
        jbBar = new javax.swing.JButton();
        jbAssociado = new javax.swing.JButton();
        jbUsuario = new javax.swing.JButton();
        jpPrincipal = new javax.swing.JPanel();
        jpAssociado = new javax.swing.JPanel();
        jspAssociado = new javax.swing.JScrollPane();
        jtAssociado = new javax.swing.JTable();
        jbAddAssociado = new javax.swing.JButton();
        jbEditAssociado = new javax.swing.JButton();
        jbRemoveAssociado = new javax.swing.JButton();
        jbRefreshAssociado = new javax.swing.JButton();
        jbAssociadoMais = new javax.swing.JButton();
        jpAssociadoMais = new javax.swing.JPanel();
        jspAssociadoMais = new javax.swing.JScrollPane();
        jtDependentes = new javax.swing.JTable();
        jbAddAssociadoMais = new javax.swing.JButton();
        jbEditAssociadoMais = new javax.swing.JButton();
        jbRemoveAssociadoMais = new javax.swing.JButton();
        jbRefreshAssociadoMais = new javax.swing.JButton();
        jbSairAnimal = new javax.swing.JButton();
        jpAssociadoInfo = new javax.swing.JPanel();
        jlNascEscrever = new javax.swing.JLabel();
        jlNasc = new javax.swing.JLabel();
        jlCPFEscrever = new javax.swing.JLabel();
        jlCPF = new javax.swing.JLabel();
        jlRGEscrever = new javax.swing.JLabel();
        jlTelefoneEscrever = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlRG1 = new javax.swing.JLabel();
        jlIDEscrever = new javax.swing.JLabel();
        jlNomeEscrever = new javax.swing.JLabel();
        jpBar = new javax.swing.JPanel();
        jspBar = new javax.swing.JScrollPane();
        jtBar = new javax.swing.JTable();
        jbAddAnimal = new javax.swing.JButton();
        jbEditAnimal = new javax.swing.JButton();
        jbRemoveAnimal = new javax.swing.JButton();
        jbRefreshAnimal = new javax.swing.JButton();
        jpUsuario = new javax.swing.JPanel();
        jspUsuario = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();
        jbAddUsuario = new javax.swing.JButton();
        jbEditUsuario = new javax.swing.JButton();
        jbRemoveUsuario = new javax.swing.JButton();
        jbRefreshUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/house.png"))); // NOI18N
        jbHome1.setToolTipText("Inicio");
        jbHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHome1ActionPerformed(evt);
            }
        });

        jbBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        jbBar.setToolTipText("Bar");
        jbBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBarActionPerformed(evt);
            }
        });

        jbAssociado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wrestler64.png"))); // NOI18N
        jbAssociado.setToolTipText("Associados");
        jbAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAssociadoActionPerformed(evt);
            }
        });

        jbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png"))); // NOI18N
        jbUsuario.setToolTipText("Usuarios");
        jbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbHome1)
                            .addComponent(jbAssociado)
                            .addComponent(jbBar)))
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addComponent(jbUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbHome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAssociado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbUsuario)
                .addGap(23, 23, 23))
        );

        jpPrincipal.setLayout(new java.awt.CardLayout());

        jpAssociado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Home"));

        jtAssociado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspAssociado.setViewportView(jtAssociado);

        jbAddAssociado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add (1).png"))); // NOI18N
        jbAddAssociado.setToolTipText("Adicionar");
        jbAddAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAssociadoActionPerformed(evt);
            }
        });

        jbEditAssociado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jbEditAssociado.setToolTipText("Editar");
        jbEditAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditAssociadoActionPerformed(evt);
            }
        });

        jbRemoveAssociado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jbRemoveAssociado.setToolTipText("Excluir");
        jbRemoveAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveAssociadoActionPerformed(evt);
            }
        });

        jbRefreshAssociado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshAssociado.setToolTipText("Atualizar");
        jbRefreshAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshAssociadoActionPerformed(evt);
            }
        });

        jbAssociadoMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/personal-information.png"))); // NOI18N
        jbAssociadoMais.setToolTipText("Atualizar");
        jbAssociadoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAssociadoMaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAssociadoLayout = new javax.swing.GroupLayout(jpAssociado);
        jpAssociado.setLayout(jpAssociadoLayout);
        jpAssociadoLayout.setHorizontalGroup(
            jpAssociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAssociadoLayout.createSequentialGroup()
                .addComponent(jspAssociado, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAssociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAssociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbAddAssociado, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbRemoveAssociado, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbRefreshAssociado, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbEditAssociado))
                    .addComponent(jbAssociadoMais)))
        );
        jpAssociadoLayout.setVerticalGroup(
            jpAssociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAssociadoLayout.createSequentialGroup()
                .addGroup(jpAssociadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspAssociado, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(jpAssociadoLayout.createSequentialGroup()
                        .addComponent(jbAddAssociado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditAssociado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRemoveAssociado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRefreshAssociado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAssociadoMais)))
                .addContainerGap())
        );

        jpPrincipal.add(jpAssociado, "card2");

        jpAssociadoMais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Home"));

        jspAssociadoMais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dependentes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jtDependentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspAssociadoMais.setViewportView(jtDependentes);

        jbAddAssociadoMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add (1).png"))); // NOI18N
        jbAddAssociadoMais.setToolTipText("Adicionar");
        jbAddAssociadoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAssociadoMaisActionPerformed(evt);
            }
        });

        jbEditAssociadoMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jbEditAssociadoMais.setToolTipText("Editar");
        jbEditAssociadoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditAssociadoMaisActionPerformed(evt);
            }
        });

        jbRemoveAssociadoMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jbRemoveAssociadoMais.setToolTipText("Excluir");
        jbRemoveAssociadoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveAssociadoMaisActionPerformed(evt);
            }
        });

        jbRefreshAssociadoMais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshAssociadoMais.setToolTipText("Atualizar");
        jbRefreshAssociadoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshAssociadoMaisActionPerformed(evt);
            }
        });

        jbSairAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reply (1)24.png"))); // NOI18N
        jbSairAnimal.setToolTipText("Voltar");
        jbSairAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairAnimalActionPerformed(evt);
            }
        });

        jpAssociadoInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jlNascEscrever.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlNascEscrever.setText("087.466.866.22");

        jlNasc.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlNasc.setText("Nasc. ");

        jlCPFEscrever.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlCPFEscrever.setText("087.466.866.22");

        jlCPF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlCPF.setText("CPF");

        jlRGEscrever.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlRGEscrever.setText("087.466.866.22");

        jlTelefoneEscrever.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlTelefoneEscrever.setText("087.466.866.22");

        jlTelefone.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlTelefone.setText("Telefone");

        jlRG1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlRG1.setText("RG");

        javax.swing.GroupLayout jpAssociadoInfoLayout = new javax.swing.GroupLayout(jpAssociadoInfo);
        jpAssociadoInfo.setLayout(jpAssociadoInfoLayout);
        jpAssociadoInfoLayout.setHorizontalGroup(
            jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAssociadoInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpAssociadoInfoLayout.createSequentialGroup()
                        .addComponent(jlCPF)
                        .addGap(18, 18, 18)
                        .addComponent(jlCPFEscrever)
                        .addGap(23, 23, 23))
                    .addGroup(jpAssociadoInfoLayout.createSequentialGroup()
                        .addComponent(jlNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNascEscrever)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAssociadoInfoLayout.createSequentialGroup()
                        .addComponent(jlTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTelefoneEscrever))
                    .addGroup(jpAssociadoInfoLayout.createSequentialGroup()
                        .addComponent(jlRG1)
                        .addGap(18, 18, 18)
                        .addComponent(jlRGEscrever)))
                .addGap(14, 14, 14))
        );
        jpAssociadoInfoLayout.setVerticalGroup(
            jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAssociadoInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlRGEscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlRG1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlNascEscrever)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAssociadoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCPFEscrever)
                    .addComponent(jlTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefoneEscrever))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jlIDEscrever.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlIDEscrever.setText("C00");

        jlNomeEscrever.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlNomeEscrever.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNomeEscrever.setText("RAFAEL");

        javax.swing.GroupLayout jpAssociadoMaisLayout = new javax.swing.GroupLayout(jpAssociadoMais);
        jpAssociadoMais.setLayout(jpAssociadoMaisLayout);
        jpAssociadoMaisLayout.setHorizontalGroup(
            jpAssociadoMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAssociadoMaisLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlIDEscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlNomeEscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jbSairAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpAssociadoMaisLayout.createSequentialGroup()
                .addGroup(jpAssociadoMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAssociadoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpAssociadoMaisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jspAssociadoMais)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAssociadoMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddAssociadoMais, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRemoveAssociadoMais, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRefreshAssociadoMais, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEditAssociadoMais))
                .addGap(8, 8, 8))
        );
        jpAssociadoMaisLayout.setVerticalGroup(
            jpAssociadoMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAssociadoMaisLayout.createSequentialGroup()
                .addGroup(jpAssociadoMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSairAnimal)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAssociadoMaisLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jpAssociadoMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlIDEscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNomeEscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAssociadoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(jpAssociadoMaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAssociadoMaisLayout.createSequentialGroup()
                        .addComponent(jbAddAssociadoMais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditAssociadoMais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRemoveAssociadoMais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRefreshAssociadoMais))
                    .addComponent(jspAssociadoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpPrincipal.add(jpAssociadoMais, "card2");

        jpBar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bar"));

        jtBar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspBar.setViewportView(jtBar);

        jbAddAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add (1).png"))); // NOI18N
        jbAddAnimal.setToolTipText("Adicionar");
        jbAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAnimalActionPerformed(evt);
            }
        });

        jbEditAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jbEditAnimal.setToolTipText("Editar");
        jbEditAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditAnimalActionPerformed(evt);
            }
        });

        jbRemoveAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jbRemoveAnimal.setToolTipText("Excluir");
        jbRemoveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveAnimalActionPerformed(evt);
            }
        });

        jbRefreshAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshAnimal.setToolTipText("Atualizar");
        jbRefreshAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBarLayout = new javax.swing.GroupLayout(jpBar);
        jpBar.setLayout(jpBarLayout);
        jpBarLayout.setHorizontalGroup(
            jpBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBarLayout.createSequentialGroup()
                .addComponent(jspBar, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRemoveAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRefreshAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEditAnimal))
                .addGap(8, 8, 8))
        );
        jpBarLayout.setVerticalGroup(
            jpBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBarLayout.createSequentialGroup()
                .addGroup(jpBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspBar, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(jpBarLayout.createSequentialGroup()
                        .addComponent(jbAddAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRemoveAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRefreshAnimal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpPrincipal.add(jpBar, "card2");

        jpUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Usuario"));

        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspUsuario.setViewportView(jtUsuario);

        jbAddUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add (1).png"))); // NOI18N
        jbAddUsuario.setToolTipText("Adicionar");
        jbAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddUsuarioActionPerformed(evt);
            }
        });

        jbEditUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jbEditUsuario.setToolTipText("Editar");
        jbEditUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditUsuarioActionPerformed(evt);
            }
        });

        jbRemoveUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jbRemoveUsuario.setToolTipText("Excluir");
        jbRemoveUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveUsuarioActionPerformed(evt);
            }
        });

        jbRefreshUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshUsuario.setToolTipText("Atualizar");
        jbRefreshUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addComponent(jspUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAddUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRemoveUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbRefreshUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbEditUsuario))
                .addGap(8, 8, 8))
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(jpUsuarioLayout.createSequentialGroup()
                        .addComponent(jbAddUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRemoveUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRefreshUsuario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpPrincipal.add(jpUsuario, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAssociadoActionPerformed
        try{
        jpPrincipal.removeAll();
        jpPrincipal.add(jpAssociado);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
        
        //----------------------
            
            //-------------BUSCA INICIO-----------
            ArrayList<Associado> lista = new DAOAssociado().buscarTodos();
            
            carregaGridAssociado(lista);          
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        } 
    }//GEN-LAST:event_jbAssociadoActionPerformed

    public void carregaGridAssociado(ArrayList<Associado> lista) {
        String[] nomeColunas = {"ID", "Nome", "Nascimento", "CPF", "RG", "Telefone"};
        DefaultTableModel dtm = new DefaultTableModel(nomeColunas, 0);
        
        for (Associado u : lista) {
            Object[] values = {u.getId(), u.getNome(), u.getDataNascimento(), u.getCpf(),
                u.getRg(), u.getTelefone()};
            dtm.addRow(values);
        }
        
        jtAssociado.setModel(dtm);
    }
//-------------BUSCA FIM-----------
    
    private void jbHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHome1ActionPerformed
        jpPrincipal.removeAll();
        jpPrincipal.add(jpBar);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
    }//GEN-LAST:event_jbHome1ActionPerformed

    private void jbBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBarActionPerformed
        jpPrincipal.removeAll();
        jpPrincipal.add(jpBar);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
    }//GEN-LAST:event_jbBarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JDViewLogin login = new JDViewLogin(this, true);
        login.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jbAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAnimalActionPerformed

    }//GEN-LAST:event_jbAddAnimalActionPerformed

    private void jbEditAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditAnimalActionPerformed

    }//GEN-LAST:event_jbEditAnimalActionPerformed

    private void jbRemoveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveAnimalActionPerformed

    }//GEN-LAST:event_jbRemoveAnimalActionPerformed

    private void jbRefreshAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshAnimalActionPerformed

    }//GEN-LAST:event_jbRefreshAnimalActionPerformed

    private void jbAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAddUsuarioActionPerformed

    private void jbEditUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEditUsuarioActionPerformed

    private void jbRemoveUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRemoveUsuarioActionPerformed

    private void jbRefreshUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRefreshUsuarioActionPerformed

    private void jbAddAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAssociadoActionPerformed
        try {
            new JDCadastroAssociados(null,true).show();
            carregaGridAssociado(new DAOAssociado().buscarTodos());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        }
    }//GEN-LAST:event_jbAddAssociadoActionPerformed

    private void jbEditAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditAssociadoActionPerformed
        //ALTERAR
        int linha = jtAssociado.getSelectedRow();
                
        if(linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma entrada da lista.");
        }else{
            int id = (int) jtAssociado.getValueAt(linha, 0);

            try {
                Associado usu = new DAOAssociado().buscarPorId(id);
                
                JDCadastroAssociados jdc = new JDCadastroAssociados(null,true);
                
                ArrayList<Associado> lista = new DAOAssociado().buscarTodos();
                
                jdc.alterarRegisto(usu);
                jdc.show();
                
                carregaGridAssociado(new DAOAssociado().buscarTodos());
                
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Driver não encontrado.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
            }
        }
    }//GEN-LAST:event_jbEditAssociadoActionPerformed

    private void jbRemoveAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveAssociadoActionPerformed
        //REMOVER
        int linha = jtAssociado.getSelectedRow();
                
        if(linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma entrada da lista.");
        }else{
            int id = (int) jtAssociado.getValueAt(linha, 0);
            if(JOptionPane.showConfirmDialog(null, "Deseja excluir a entrada selecionada?") == JOptionPane.YES_OPTION){
                
                try {
                    
                    Associado u = new Associado();
                    u.setId(id);
                    new DAOAssociado().apagar(u);
                    carregaGridAssociado(new DAOAssociado().buscarTodos());
                    JOptionPane.showMessageDialog(null, "Registro excluido com sucesso.");
                    
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Driver não encontrado.");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
                }
            }
        }
    }//GEN-LAST:event_jbRemoveAssociadoActionPerformed

    private void jbRefreshAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshAssociadoActionPerformed
        //ATUALIZAR
        try {
            carregaGridAssociado(new DAOAssociado().buscarTodos());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        }
    }//GEN-LAST:event_jbRefreshAssociadoActionPerformed

    private void jbAssociadoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAssociadoMaisActionPerformed
        
        //QUNDO CLICAR NO BOTAO PRA IR PRO MAIS
        try{
//        jpPrincipal.removeAll();
//        jpPrincipal.add(jpAssociadoMais);
//        jpPrincipal.repaint();
//        jpPrincipal.revalidate();
        
        //----------------------
        //TESTE INICIO
        int linha = jtAssociado.getSelectedRow();
                
        if(linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma entrada da lista.");
            
        }else{
            jpPrincipal.removeAll();
            jpPrincipal.add(jpAssociadoMais);
            jpPrincipal.repaint();
            jpPrincipal.revalidate();
        
            int id = (int) jtAssociado.getValueAt(linha, 0);
                
                Associado ass = new DAOAssociado().buscarPorId(id);
                
                jlIDEscrever.setText(String.valueOf(ass.getId()));
                jlCPFEscrever.setText(String.valueOf(ass.getCpf()));
                jlRGEscrever.setText(String.valueOf(ass.getRg()));
                jlNomeEscrever.setText(String.valueOf(ass.getNome()));
                jlTelefoneEscrever.setText(String.valueOf(ass.getTelefone()));
                jlNascEscrever.setText(String.valueOf(ass.getDataNascimento()));
                
//                ArrayList<Usuario> lista = new DAOUsuario().buscarTodos();
//            
//                carregaGridUsuarios(lista);   
            
//                JDCadastroAssociados jdc = new JDCadastroAssociados(null,true);
//                
//                
                
//                jdc.alterarRegisto(usu);
//                jdc.show();
//                
            
        
        //TESTE FIM
            
            //-------------BUSCA INICIO-----------
//            ArrayList<Dependente> lista = new DAODependente().buscarTodos();
              ArrayList<Dependente> lista = new DAODependente().getDependenteAssociado(ass.getId());
            
            carregaGridDependentes(lista);  
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        } 
    }//GEN-LAST:event_jbAssociadoMaisActionPerformed
    
    
    public void carregaGridDependentes(ArrayList<Dependente> lista) {
        String[] nomeColunas = {"ID", "Nome", "Nascimento", "Tipo"};
        DefaultTableModel dtm = new DefaultTableModel(nomeColunas, 0);
        
        for (Dependente u : lista) {
            Object[] values = {u.getId(), u.getNome(), u.getDataNascimento(), u.getTipo()};
            dtm.addRow(values);
        }
        
        jtDependentes.setModel(dtm);
    }
//-------------BUSCA FIM-----------
    
    public void carregaGridDependenteEspecifico() throws ClassNotFoundException, SQLException {
        int linha = jtAssociado.getSelectedRow();
        int idAss = (int) jtAssociado.getValueAt(linha, 0);
        
        Associado ass = new DAOAssociado().buscarPorId(idAss);
        
        ArrayList<Dependente> lista = new DAODependente().getDependenteAssociado(ass.getId());

        String[] nomeColunas = {"ID", "Nome", "Nascimento", "Tipo"};
        DefaultTableModel dtm = new DefaultTableModel(nomeColunas, 0);
        
        for (Dependente u : lista) {
            Object[] values = {u.getId(), u.getNome(), u.getDataNascimento(), u.getTipo()};
            dtm.addRow(values);
        }
        
        jtDependentes.setModel(dtm);
    }
    
    
    private void jbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuarioActionPerformed
        jpPrincipal.removeAll();
        jpPrincipal.add(jpUsuario);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
    }//GEN-LAST:event_jbUsuarioActionPerformed

    private void jbAddAssociadoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAssociadoMaisActionPerformed
        try {
            int linha = jtAssociado.getSelectedRow();
            int id = (int) jtAssociado.getValueAt(linha, 0);
            Associado ass = new DAOAssociado().buscarPorId(id);
            
            new JDCadastroDependentes(null, true, ass).show();
            
//            new JDCadastroDependentes(null,true).show();
//            ArrayList<Dependente> lista = new DAODependente().getDependenteAssociado(ass.getId());
            
            carregaGridDependenteEspecifico();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        }
    }//GEN-LAST:event_jbAddAssociadoMaisActionPerformed

    private void jbEditAssociadoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditAssociadoMaisActionPerformed
        //ALTERAR
        int row = jtDependentes.getSelectedRow();
                
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma entrada da lista.");
        }else{
            int id = (int) jtDependentes.getValueAt(row, 0);

            try {
                
                Dependente usu = new DAODependente().buscarPorId(id);
                
                JDCadastroDependentes jdc = new JDCadastroDependentes(null, true);
                
//                ArrayList<Associado> lista = new DAOAssociado().buscarTodos();
                
                jdc.alterarRegisto(usu);
                jdc.show();
                
                carregaGridDependenteEspecifico();
                
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Driver não encontrado.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
            }
        }
    }//GEN-LAST:event_jbEditAssociadoMaisActionPerformed

    private void jbRemoveAssociadoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveAssociadoMaisActionPerformed
        //REMOVER
        int row = jtDependentes.getSelectedRow();
                
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma entrada da lista.");
        }else{
            int id = (int) jtDependentes.getValueAt(row, 0);
            if(JOptionPane.showConfirmDialog(null, "Deseja excluir a entrada selecionada?") == JOptionPane.YES_OPTION){
                
                try {
                    
                    Dependente u = new Dependente();
                    u.setId(id);
                    new DAODependente().apagar(u);
                    
                    carregaGridDependenteEspecifico();
                    
//                    ////////////
//                    int linha = jtAssociado.getSelectedRow();
//                    int idAss = (int) jtAssociado.getValueAt(linha, 0);
//                    Associado ass = new DAOAssociado().buscarPorId(idAss);
//                    ArrayList<Dependente> lista = new DAODependente().getDependenteAssociado(ass.getId());
//                    ////////////
                    JOptionPane.showMessageDialog(null, "Registro excluido com sucesso.");
                    
                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Driver não encontrado.");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
                }
            }
        }
    }//GEN-LAST:event_jbRemoveAssociadoMaisActionPerformed

    private void jbRefreshAssociadoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshAssociadoMaisActionPerformed
        //ATUALIZAR
        try {
//            int linha = jtAssociado.getSelectedRow();
//            int id = (int) jtAssociado.getValueAt(linha, 0);
//            Associado ass = new DAOAssociado().buscarPorId(id);
//            ArrayList<Dependente> lista = new DAODependente().getDependenteAssociado(ass.getId());

            carregaGridDependenteEspecifico();
            
//            carregaGridDependentes(lista); 
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        }
    }//GEN-LAST:event_jbRefreshAssociadoMaisActionPerformed

    private void jbSairAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairAnimalActionPerformed
        jpPrincipal.removeAll();
        jpPrincipal.add(jpAssociado);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
    }//GEN-LAST:event_jbSairAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddAnimal;
    private javax.swing.JButton jbAddAssociado;
    private javax.swing.JButton jbAddAssociadoMais;
    private javax.swing.JButton jbAddUsuario;
    private javax.swing.JButton jbAssociado;
    private javax.swing.JButton jbAssociadoMais;
    private javax.swing.JButton jbBar;
    private javax.swing.JButton jbEditAnimal;
    private javax.swing.JButton jbEditAssociado;
    private javax.swing.JButton jbEditAssociadoMais;
    private javax.swing.JButton jbEditUsuario;
    private javax.swing.JButton jbHome1;
    private javax.swing.JButton jbRefreshAnimal;
    private javax.swing.JButton jbRefreshAssociado;
    private javax.swing.JButton jbRefreshAssociadoMais;
    private javax.swing.JButton jbRefreshUsuario;
    private javax.swing.JButton jbRemoveAnimal;
    private javax.swing.JButton jbRemoveAssociado;
    private javax.swing.JButton jbRemoveAssociadoMais;
    private javax.swing.JButton jbRemoveUsuario;
    private javax.swing.JButton jbSairAnimal;
    private javax.swing.JButton jbUsuario;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCPFEscrever;
    private javax.swing.JLabel jlIDEscrever;
    private javax.swing.JLabel jlNasc;
    private javax.swing.JLabel jlNascEscrever;
    private javax.swing.JLabel jlNomeEscrever;
    private javax.swing.JLabel jlRG1;
    private javax.swing.JLabel jlRGEscrever;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlTelefoneEscrever;
    private javax.swing.JPanel jpAssociado;
    private javax.swing.JPanel jpAssociadoInfo;
    private javax.swing.JPanel jpAssociadoMais;
    private javax.swing.JPanel jpBar;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JScrollPane jspAssociado;
    private javax.swing.JScrollPane jspAssociadoMais;
    private javax.swing.JScrollPane jspBar;
    private javax.swing.JScrollPane jspUsuario;
    private javax.swing.JTable jtAssociado;
    private javax.swing.JTable jtBar;
    private javax.swing.JTable jtDependentes;
    private javax.swing.JTable jtUsuario;
    // End of variables declaration//GEN-END:variables
}
