/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.vianna.aula.trabalhoprincipalclube.view;

/**
 *
 * @author suporte
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMenu = new javax.swing.JPanel();
        jbHome1 = new javax.swing.JButton();
        jbHome2 = new javax.swing.JButton();
        jbHome3 = new javax.swing.JButton();
        jpPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jspAnimais = new javax.swing.JScrollPane();
        jtAnimais = new javax.swing.JTable();
        jbAddAnimal = new javax.swing.JButton();
        jbEditAnimal = new javax.swing.JButton();
        jbRemoveAnimal = new javax.swing.JButton();
        jbRefreshAnimal = new javax.swing.JButton();
        jbRefreshAnimal1 = new javax.swing.JButton();
        jbRefreshAnimal2 = new javax.swing.JButton();
        jbRefreshAnimal3 = new javax.swing.JButton();
        jbRefreshAnimal4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jbHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home64.png"))); // NOI18N
        jbHome1.setToolTipText("Inicio");
        jbHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHome1ActionPerformed(evt);
            }
        });

        jbHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar.png"))); // NOI18N
        jbHome2.setToolTipText("Inicio");
        jbHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHome2ActionPerformed(evt);
            }
        });

        jbHome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wrestler64.png"))); // NOI18N
        jbHome3.setToolTipText("Inicio");
        jbHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHome3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbHome1)
                    .addComponent(jbHome3)
                    .addComponent(jbHome2)))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbHome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbHome2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbHome3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPrincipal.setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Home"));

        jtAnimais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspAnimais.setViewportView(jtAnimais);

        jbAddAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add (1).png"))); // NOI18N
        jbAddAnimal.setToolTipText("Adicionar");
        jbAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddAnimalActionPerformed(evt);
            }
        });

        jbEditAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        jbEditAnimal.setToolTipText("Editar");
        jbEditAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditAnimalActionPerformed(evt);
            }
        });

        jbRemoveAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash.png"))); // NOI18N
        jbRemoveAnimal.setToolTipText("Excluir");
        jbRemoveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoveAnimalActionPerformed(evt);
            }
        });

        jbRefreshAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshAnimal.setToolTipText("Atualizar");
        jbRefreshAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshAnimalActionPerformed(evt);
            }
        });

        jbRefreshAnimal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshAnimal1.setToolTipText("Atualizar");

        jbRefreshAnimal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshAnimal2.setToolTipText("Atualizar");

        jbRefreshAnimal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jbRefreshAnimal3.setToolTipText("Atualizar");

        jbRefreshAnimal4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/family (32).png"))); // NOI18N
        jbRefreshAnimal4.setToolTipText("Atualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jspAnimais, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbAddAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbRemoveAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbRefreshAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbEditAnimal))
                    .addComponent(jbRefreshAnimal4)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbRefreshAnimal1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbRefreshAnimal2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbRefreshAnimal3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspAnimais, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbAddAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRemoveAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbRefreshAnimal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRefreshAnimal4)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbRefreshAnimal1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbRefreshAnimal2)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbRefreshAnimal3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jpPrincipal.add(jPanel1, "card2");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro de Associados"));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpPrincipal.add(jPanel2, "card2");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "xfdgdg"));

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel3)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        jpPrincipal.add(jPanel3, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHome3ActionPerformed
        jpPrincipal.removeAll();
        jpPrincipal.add(jPanel3);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
    }//GEN-LAST:event_jbHome3ActionPerformed

    private void jbHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHome1ActionPerformed
        jpPrincipal.removeAll();
        jpPrincipal.add(jPanel1);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
    }//GEN-LAST:event_jbHome1ActionPerformed

    private void jbHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHome2ActionPerformed
        jpPrincipal.removeAll();
        jpPrincipal.add(jPanel2);
        jpPrincipal.repaint();
        jpPrincipal.revalidate();
    }//GEN-LAST:event_jbHome2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JDViewLogin login = new JDViewLogin(this, true);
        login.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jbAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddAnimalActionPerformed
        try {
            new JDAnimais(null,true).show();
            carregaGridAnimais(new DAOAnimal().buscarTodos());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        }
    }//GEN-LAST:event_jbAddAnimalActionPerformed

    private void jbEditAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditAnimalActionPerformed
        //ALTERAR
        int linha = jtAnimais.getSelectedRow();

        if(linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma entrada da lista.");
        }else{
            int id = (int) jtAnimais.getValueAt(linha, 0);

            try {
                Animal usu = new DAOAnimal().buscarPorId(id);

                JDAnimais jdc = new JDAnimais(null,true);

                ArrayList<Animal> lista = new DAOAnimal().buscarTodos();

                jdc.alterarRegisto(usu);
                jdc.show();

                carregaGridAnimais(new DAOAnimal().buscarTodos());

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Driver não encontrado.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
            }

        }
    }//GEN-LAST:event_jbEditAnimalActionPerformed

    private void jbRemoveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoveAnimalActionPerformed
        //REMOVER
        int linha = jtAnimais.getSelectedRow();

        if(linha < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma entrada da lista.");
        }else{
            int id = (int) jtAnimais.getValueAt(linha, 0);
            if(JOptionPane.showConfirmDialog(null, "Deseja excluir a entrada selecionada?") == JOptionPane.YES_OPTION){

                Animal u;

                try {
                    if(jtAnimais.getValueAt(linha, 0) == "GATO"){
                        u = new Gato();
                    } else {
                        u = new Cachorro();
                    }
                    u.setId(id);
                    new DAOAnimal().apagar(u);
                    carregaGridAnimais(new DAOAnimal().buscarTodos());
                    JOptionPane.showMessageDialog(null, "Registro excluido com sucesso.");

                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "Driver não encontrado.");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
                }
            }
        }
    }//GEN-LAST:event_jbRemoveAnimalActionPerformed

    private void jbRefreshAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshAnimalActionPerformed
        //ATUALIZAR
        try {
            carregaGridAnimais(new DAOAnimal().buscarTodos());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não encontrado.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na conexão com o banco ou na consulta.");
        }
    }//GEN-LAST:event_jbRefreshAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbAddAnimal;
    private javax.swing.JButton jbEditAnimal;
    private javax.swing.JButton jbHome1;
    private javax.swing.JButton jbHome2;
    private javax.swing.JButton jbHome3;
    private javax.swing.JButton jbRefreshAnimal;
    private javax.swing.JButton jbRefreshAnimal1;
    private javax.swing.JButton jbRefreshAnimal2;
    private javax.swing.JButton jbRefreshAnimal3;
    private javax.swing.JButton jbRefreshAnimal4;
    private javax.swing.JButton jbRemoveAnimal;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JScrollPane jspAnimais;
    private javax.swing.JTable jtAnimais;
    // End of variables declaration//GEN-END:variables
}
